name: ReadyAPI Tests

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  readyapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull ReadyAPI Docker image
        run: docker pull smartbear/ready-api-soapui-testrunner:latest

      - name: Run ReadyAPI Tests
        env:
          PROJECT_FILE: DemoAppProject.xml
          TEST_SUITE: DemoAppProject
        run: |
          mkdir -p test-results
          docker run --rm \
            -v "${{ github.workspace }}:/readyapi" \
            -v "${{ github.workspace }}/test-results:/test-results" \
            smartbear/ready-api-soapui-testrunner:latest \
            /readyapi/${PROJECT_FILE} \
            -s "${TEST_SUITE}" \
            -j \
            -f /test-results

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: readyapi-test-results
          path: test-results/